/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_NativeLibrary */

#ifndef _Included_com_example_NativeLibrary
#define _Included_com_example_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_NativeLibrary
 * Method:    cudaRidgeDetection
 * Signature: ([F[FIIFF)V
 */
__attribute__((unused)) __attribute__((unused)) JNIEXPORT void JNICALL Java_com_example_NativeLibrary_cudaRidgeDetection
(JNIEnv *, jclass, jfloatArray, jfloatArray, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
